version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack --stack-name my-stack-${CIRCLE_WORKFLOW_ID}

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Stack
          command: |
            aws cloudformation deploy \
              --template-file cfn_template.yaml \
              --stack-name my-stack-${CIRCLE_WORKFLOW_ID}
      - run: return 1
      - destroy_environment
        when: on_fail

workflows:
  my_workflow:
    jobs:
      - create_infrastructure                                       
